---
- name: Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ ansible_distribution | lower }}.yml"
      paths: vars

- include: ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    # - [[ $(lspci | grep -i nvidia) ]]

- name: Add {{cuda_path_bin}} to PATH
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=(["]*)((?!.*?{{cuda_path_bin}}).*?)(["]*)$'
    line: 'PATH=\1{{cuda_path_bin}}:\2\3'
