---
# Alternative to: apt-get install linux-headers-$(uname -r)
- name: CUDA | Install kernel headers and development packages.
  package:
    name: linux-headers-{{ansible_kernel}}
    state: present

- include: ubuntu1404.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"

- include: ubuntu1604.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"

- name: CUDA | Install cuda package from repository
  apt:
    name: cuda
    state: latest
    update_cache: yes
